### ISSUE TITLE
recommended value for -k skip-count ?

### ISSUE THREAD

**Issue by mailinglists35** [AMDmi3/ssdaligntest#1]
thanks.

**Comment by AMDmi3** [comment]
You don't need it generally. It may be useful in (pure theoretical) cases where you do multiple consequent tests on the same device AND some kind of caching is involved (which shouldn't be the case if you run on raw devices). In this case sectors read during the first test run may be cached and if you run the test again you'll have blocks read from memory and not the disk, rendering the test useless. For such a case you could increment `-k` by your `-c` value each test run, to use another area of the disk which has not been cached yet.

**Comment by mailinglists35** [comment]
great, thank you! :)
